### ISSUE TITLE
question: code execution before and after package is loaded

### ISSUE THREAD

**Issue by suconakh** [phikal/setup.el#2]
How exactly can I reproduce the behavior of use-package's `: init` and`: config` in setup.el? Do I need to create my own keywords for it, or can I somehow use the builtin functionality to execute the code BEFORE and AFTER loading the package? There is a keyword `: when-loaded`, but the documentation says that I should avoid using it whenever possible. Why is this so? And what happens to code in the body of a macro that is not keywords? Will it be executed before or after downloading the package? 
Also i tried to use macroexpand to understand how some keywords work and came across one function in the `:option` keyword that i don't understand: `custom-load-symbol`. The docs says it loads all dependencies for symbol but does than mean if i use `:option` keyword it will load my package before i actually want to?
Another question, is it possible to hook some code before and after loading any package? For example, to replicate `use-package-verbose` so that I can debug my load order and find packages that load immediately.

**Comment by phikal** [comment]
> How exactly can I reproduce the behavior of use-package's : init and: config in setup.el?

All code that is written directly in a setup body is comparable to `:init`, in the sense that is will be evaluated at the same time the setup body (or it's expansion) is evaluated. You are right that to replicate `:config`, you will need to use `:when-loaded`.  The reason I advise against it it that for most use-cases, it would be better to write your own local macro that generates to deferred code. But `:when-loaded` is still part of setup.el, because in some cases packages require special, custom code to be evaluated (which I consider bad style), so you can still use it if you want to.

I should probably update that docstring to clarify the warning, as you aren't the first to be confused by it...

> And what happens to code in the body of a macro that is not keywords? Will it be executed before or after downloading the package?

Macros are all expanded before the body is evaluated, so (if I am understanding the question correctly) any macro with side effects would have these side effects triggered before the body is executed.

If this is not what you meant, could you give me an example?

> Also i tried to use macroexpand to understand how some keywords work and came across one function in the :option keyword that i don't understand: custom-load-symbol.

This might be seen as controversial, but it is essentially what `customize-set-variable` does too. If you want to access the setter and getter that an autoloaded option might provide, you have to load it first. For regular options that are not autoloaded, this shouldn't do anything, so you have to check and make sure for yourself if this is what you want or not.  Otherwise, using `setq` or your own local macro is just a good as `:option` -- there is nothing inherently special about the defaults (you are free to throw everything away!).

>  Another question, is it possible to hook some code before and after loading any package? For example, to replicate use-package-verbose so that I can debug my load order and find packages that load immediately.

We do have the `setup-modifier-list` that wraps the expanded setup body.  You could add a function that generates the code you want, but there is nothing directly comparable.

**Comment by suconakh** [comment]
Thanks for the detailed answer, it clarified a lot!

**Comment by phikal** [comment]
"Conakh S.U." ***@***.***> writes:

> Thanks for the detailed answer, it clarified a lot! 

Should we close the issue then?

Also, for specific questions feel free to ping me on Libera (my nick is
pkal), or send a message to the mailing list.

-- 
	Philip Kaludercic

**Comment by suconakh** [comment]
Sure, thanks!
